prometheus/cloudwatch_exporter

README.md, pom.xml, src/main/java/io/prometheus/cloudwatch/CloudwatchCollector.java, src/main/java/io/prometheus/cloudwatch/WebServer.java, src/test/java/io/prometheus/cloudwatch/CloudwatchCollectorTest.java
Cloudwatch has been reported to take a few minutes
to converge on values, so as we don't have a way to update
old values wait a bit to be safe.
=> Don't request the freshest data, wait a bit.

src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java, src/test/java/io/prometheus/cloudwatch/CloudWatchCollectorTest.java
for period_seconds, range_seconds, delay_seconds.
Should fix issue https://github.com/prometheus/cloudwatch_exporter/issues/4.
cc: @fstehle @bracki
=> fix json integer parsing

src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java, src/test/java/io/prometheus/cloudwatch/CloudWatchCollectorTest.java
Enhancement to PR https://github.com/prometheus/cloudwatch_exporter/pull/6
Add wildcard matching to dimension selection.
=> Add wildcard matching to dimension selection

pom.xml
As per https://github.com/prometheus/cloudwatch_exporter/issues/23
=> org.yaml.snakeyaml 1.17 without SNAPSHOT

README.md
Trivial change to fix up a curl command in the README.
@brian-brazil
=> Correct curl POST command

Dockerfile, README.md
Signed-off-by: Martin Lee <martin@billforward.net>
=> Move config file to cmd so it can be set when running the container

example.yml
Signed-off-by: jeff.wenzbauer <jwenz723@gmail.com>
=> Added S3 example into example.yml

Dockerfile
so the port and Author are set correctly in the released image.
PTAL @brian-brazil
=> Move EXPOSE and MAINTAINER to final build stage

README.md
Prices are still the same.
Signed-off-by: Brian Brazil <brian.brazil@robustperception.io>
=> Add a bit more on timestamps.

src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java
Add "action" and "namespace" to "cloudwatch_requests_total".
This change allowed me to get the insights for #143.
=> Add labels to "cloudwatch_requests_total"

example.yml
This was inconsistent with the README and the code.
=> fix example.yml to use proper config names

.circleci/config.yml
Signed-off-by: Brian Brazil <brian.brazil@robustperception.io>
=> Add circleci for testing.

README.md, src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java
=> Auto detect AWS region if none is specified

src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java, src/main/java/io/prometheus/cloudwatch/WebServer.java
(also sorts imports)
This is basically https://github.com/prometheus/cloudwatch_exporter/pull/192 
but I have DCO signed... so this can get merged.
=> Close the FileReader

src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java
=> Return tag _info when there's no tag_selections

src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java, src/test/java/io/prometheus/cloudwatch/CloudWatchCollectorTest.java
=> Handle dynamo metrics without configured dimensions.

README.md
Clarify by adding a header for people looking for instructions on working with AWS tags. 
Also provide an example query to explain how one can use PromQL for the purpose of filtering based on tags.
@brian-brazil
=> Add header and example for tags to readme

src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java
Signed-off-by: Mikhail Advani <mikhail.advani@gmail.com>
=> Fixes #297. Single aws_resource_info per tag_selection metric block

pom.xml
Signed-off-by: Brian Brazil <brian.brazil@robustperception.io>
=> Update to client_java 0.10.0 to pull in OpenMetrics support.

Dockerfile
use LABEL as recommended; use "The Prometheus Authors" as in most other
projects.
=> Replace deprecated MAINTAINER statement in Dockerfile

.circleci/config.yml
=> Bump JDK to 11 in CircleCI

pom.xml
Minor version bump of Jetty to one with less open CVEs
=> Bumping version of Jetty to one with less open CVEs

pom.xml
This makes it possible to query RDS Proxy metrics. https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/rds-proxy.html#rds-proxy.monitoring
=> Update awssdk to 2.16.64

README.md
@rakyll FYI. Please LGTM this one once you're reasonably happy with https://github.com/prometheus-community/ecs_exporter
=> Refer to ECS exporter in README

pom.xml, src/main/java/io/prometheus/cloudwatch/WebServer.java
Should be useful for sizing and resource use cases.
=> Add JVM hotspot metrics

README.md, pom.xml, src/main/java/io/prometheus/cloudwatch/BuildInfoCollector.java, src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java, src/main/java/io/prometheus/cloudwatch/WebServer.java, src/main/resources/.properties, src/test/java/io/prometheus/cloudwatch/CloudWatchCollectorTest.java
cleanup and commit squash for PR https://github.com/prometheus/cloudwatch_exporter/pull/397
=> Build info metric feature

.dockerignore, Dockerfile
broken since #401 . No images for 0.13.0 can be found.
=> Fix docker image build

examples/ApplicationELB.yml
duplicated metrics cause issues on prometheus
=> Removing duplicated metrics

src/main/java/io/prometheus/cloudwatch/WebServer.java
=> Fixing leaking FileReader on WebServer

src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java, src/main/java/io/prometheus/cloudwatch/DataGetter.java, src/main/java/io/prometheus/cloudwatch/GetMetricDataDataGetter.java, src/main/java/io/prometheus/cloudwatch/GetMetricStatisticsDataGetter.java
=> Fixed null unit in HELP in case of GetMetricStatistics

examples/DynamoDB.yml
Signed-off-by: Yonah Dissen <yonahdissen@gmail.com>
=> add dynamoDB example

examples/EC2.yml
Issue: #430
Remove duplicated entry from example
=> #430 remove duplicated entry in examples

pom.xml
https://github.com/prometheus/client_java/releases/tag/parent-0.16.0
=> Update client_java to 0.16

examples/Kafka.yml
=> Add kafka example config

examples/AuroraServerless
Signed-off-by: Nick Marchini <28953812+nmarchini@users.noreply.github.com>
=> Adding Example for Aurora Serverless V2

examples/DocumentDB.yml
=> add DocumentDB example

pom.xml
to address security issues. cc @jjneely
=> Update jetty-servlet to 11.0.13

.github/workflows/maven.yml, examples/Sagemaker.yml, pom.xml
To add example of exporting AWS SageMaker CloudWatch metrics to Prometheus
=> Add example for sagemaker

examples/SES.yml
=> add SES example

.github/workflows/maven.yml
Due to advanced-security/maven-dependency-submission-action#65.
=> Downgrade advanced-security/maven-dependency-submission-action action

examples/ApplicationELB.yml
=> Increase delay for ConsumedLCUs in ApplicationELB example

examples/dashboards/DocumentDB.yml
Hello team, I was able to create Kubernetes Grafana dashboard for DocumentDB
Hope it will be a good example 
@matthiasr
=> Add DocumentDB Grafana dashboard

.github/workflows/maven.yml, Dockerfile, RELEASING.md
We've been using it for tests for a while already (#657). Into the future /o/
=> Update to Java 21 for releases

examples/NATGateway.yml
This change fixes  indentation on NATGateway.yml.
=> fix NATGateway.yml indentation
