prometheus/cloudwatch_exporter

- README.md
- src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java
- src/test/java/io/prometheus/cloudwatch/CloudWatchCollectorTest.java
In order to avoid fetching all metrics for one Namespace (eg. `AWS/ELB`), I would like to introduce the possibility to filter metrics, by a metric dimension value.
That allows to have the following config to only get metrics for a single ELB named `myLB`:
```
{
"region": "eu-west-1",
"delay_seconds": 600,
"metrics": [
{
"aws_namespace": "AWS/ELB",
"aws_metric_name": "RequestCount",
"aws_dimensions": [
"AvailabilityZone",
"LoadBalancerName:myLB"
],
"aws_statistics": ["Sum"],
"period_seconds": 300
}
]
}
```
> Allow filtering of metrics by dimension values

- src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java
Use the help text if it is provided in the description, otherwise use the generated help text.
> Use the help text when it is specified in the rule

- pom.xml
We need to update the version for the AWS Java SDK Cloudwatch to get the metrics for AWS Aurora.
Cheers
> updated dependency version for AWS Java SDK Cloudwatch to 1.10.34

- Dockerfile
- README.md
It's rather confusing to have config.json containing yaml-formatted text.  This updates the Dockerfile (and the readme) to use config.yml instead.
> Use config.yml instead of config.json

- README.md
- pom.xml
- src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java
This allows us to start a cloudwatch_exporter which can query metrics from another AWS account.
cc: @bracki
The cloudformation template we use:
```json
{
"Resources": {
"GrantReadAccessToAnotherAccount": {
"Properties": {
"AssumeRolePolicyDocument": {
"Statement": [
{
"Action": [
"sts:AssumeRole"
],
"Effect": "Allow",
"Principal": {
"AWS": [
"arn:aws:iam::YOUR_ACCOUNT_HERE:root"
]
}
}
],
"Version": "2012-10-17"
},
"ManagedPolicyArns": [
"arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess"
]
},
"Type": "AWS::IAM::Role"
}
}
}
```
> introduce optional role_arn for retrieving cross account metrics.

- src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java
- src/test/java/io/prometheus/cloudwatch/CloudWatchCollectorTest.java
Rather than build the endpoint ourselves, use the support from the AWS SDK to do it for us.
> Address #28 by using AWS-SDK to fetch monitoring endpoint.

- pom.xml
I was trying to use this exporter behind an http proxy, and after upgrading the following libraries, I was successfull.
- com.amazonaws.aws-java-sdk-cloudwatch => 1.11.86
- com.amazonaws.aws-java-sdk-sts        => 1.11.86
- io.prometheus.simpleclient            => 0.0.20
- io.prometheus.simpleclient_servlet    => 0.0.20
> Upgrade pom.xml dependencies for proxy support

- src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java
- src/test/java/io/prometheus/cloudwatch/CloudWatchCollectorTest.java
It's expected that the user will set honor_labels
for the cloudwatch exporter, so we should
explicitly set both job and instance.
> Set instance label to empty

- README.md
- src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java
- src/test/java/io/prometheus/cloudwatch/CloudWatchCollectorTest.java
This adds support for [extended statistics](https://aws.amazon.com/blogs/aws/amazon-cloudwatch-update-percentile-statistics-and-new-dashboard-widgets/), which can be used to obtain percentile values for certain Cloudwatch metrics.
A config such as
```yaml
---
region: us-east-1
metrics:
- aws_namespace: AWS/ELB
aws_metric_name: Latency
aws_dimensions: [LoadBalancerName]
aws_dimension_select:
LoadBalancerName: ["my-test-elb"]
aws_extended_statistics: ["p95", "p99.99"]
```
will result in
```
aws_elb_latency_p99.99{job="aws_elb",instance="",load_balancer_name="my-test-elb",} 1.883888000527654
aws_elb_latency_p95{job="aws_elb",instance="",load_balancer_name="my-test-elb",} 0.20261543373300783
```
Some notes on implementation:
* I've exposed the underlying API more or less directly. It requires …
> Add support for Cloudwatch extended statistics

- README.md
- src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java
- src/test/java/io/prometheus/cloudwatch/CloudWatchCollectorTest.java
This is my attempt at fixing the issue described in #18. I'm not too experienced with Java, so please let me know if anything looks stupid and I'll fix it up.
As was suggested in the linked issue this modifies `baseName` when scraping metrics from AWS/DynamoDB and fanning out across the GlobalSecondaryIndexName namespace.
That is, given a config.yaml like the below
```yaml
---
region: us-east-1
metrics:
- aws_namespace: AWS/DynamoDB
aws_metric_name: ConsumedReadCapacityUnits
aws_dimensions: [TableName, GlobalSecondaryIndexName]
aws_dimension_select:
TableName: ["my-test-table"]
aws_statistics: [Sum]
- aws_namespace: AWS/DynamoDB
aws_metric_name: ConsumedReadCapacityUnits
aws_dimensions: [TableName]
aws_dimension_select:
TableName: ["my-test-table"]
aws_statistics: [Sum]
```
a scrape will …
> Avoid generating duplicate help text for DynamoDB

- Dockerfile
- README.md
as per https://github.com/prometheus/cloudwatch_exporter/issues/67 and https://github.com/prometheus/cloudwatch_exporter/issues/54
> Use /config/config.yml because it is more friendly to kubernetes.

- README.md
- src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java
- src/main/java/io/prometheus/cloudwatch/DynamicReloadServlet.java
- src/main/java/io/prometheus/cloudwatch/ReloadSignalHandler.java
- src/main/java/io/prometheus/cloudwatch/WebServer.java
- src/test/java/io/prometheus/cloudwatch/CloudWatchCollectorTest.java
Adds an endpoint to dynamically reload the yaml configuration via `curl -X POST localhost:9106/-/reload`.
The `rules` list is now wrapped in a `synchronized` block for consistent object access during updates.
> Configuration reload endpoint

- README.md
- pom.xml
- src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java
Hello!
Here are timestamps for displaying delayed cloudwatch metrics in prometheus correctly.
This patch was deployed to our environment and it works. https://github.com/prometheus/cloudwatch_exporter/issues/22
> Add timestamps to exported metrics

- README.md
- src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java
- src/test/java/io/prometheus/cloudwatch/CloudWatchCollectorTest.java
Resolves #100 by allowing users to configure whether Cloudwatch timestamps are sent with metrics
Have tested locally and in our own environment 👍
> Toggle Cloudwatch timestamps on a per-metric basis

- example.yml
Add CloudFront exampless
- Region must be set to `us-east-1`
- `aws_dimensions` must be `[DistributionId, Region]`
- `aws_dimensions_select` must be `Region: [Global]`
See: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cf-metricscollected.html
> Add CloudFront examples

- src/main/java/io/prometheus/cloudwatch/HealthServlet.java
- src/main/java/io/prometheus/cloudwatch/WebServer.java
I wanted to have a k8s pod for running my cloud watch exporter, but no readiness/health endpoint exists
Add one. These seem a little bit silly (they both just respond if the server is running, and don't say anything about the status of the connection to AWS (I took inspiration from prometheus: https://github.com/prometheus/prometheus/blob/2bd510a63e48ac6bf4971d62199bdb1045c93f1a/web/web.go#L297-L304) 
This also addresses: https://github.com/prometheus/cloudwatch_exporter/issues/32, which was closed but... @brian-brazil
> add health/ready endpoints

- Dockerfile
The "java" image on Docker Hub is deprecated and has not received any updates since 2016-12-31. This PR changes the base image to `openjdk:10` and `openjdk:10-jre-slim` for the runtime image. Java 10 is the latest stable version.
To make the final Docker image, a [multi step build](https://docs.docker.com/develop/develop-images/multistage-build/) can be used. The project is compiled in the "builder" step, and the jar is copied over to the "runner" build step.
The new image size is 293MB instead of 767MB.
> Improved Dockerfile: Seperate runtime and buildtime images, use openjdk instead of java

- Dockerfile
- pom.xml
Fixes #156. Have built this locally and confirmed it's working with our configuration.
I had to patch `pom.xml` to workaround an upstream Debian bug,
* https://github.com/docker-library/openjdk/issues/247
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=911925
> Bump dockerfile to Java 11

- pom.xml
Older versions of the jackson-databind library have the following remote code execution vulnerabilities:
- [CVE-2018-5968](https://nvd.nist.gov/vuln/detail/CVE-2018-5968)
- [CVE-2017-17485](https://nvd.nist.gov/vuln/detail/CVE-2017-17485)
- [CVE-2017-7525](https://nvd.nist.gov/vuln/detail/CVE-2017-7525)
- [CVE-2017-15095](https://nvd.nist.gov/vuln/detail/CVE-2017-15095)
- [CVE-2018-7489](https://nvd.nist.gov/vuln/detail/CVE-2018-7489)
These have been fixed in version 2.9.7.
cc @brian-brazil
> Upgrade jackson-databind to version 2.9.7 due to security vulnerabilities

- pom.xml
We want this newer version to address CVEs [2018-19360](http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2018-19360), [2018-19361](http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2018-19361) and [2018-19362](http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2018-19362).
> @brian-brazil Update jackson-databind to 2.9.8

- README.md
- pom.xml
We would like to update jetty-servlet to 9.4.15.v20190215 in order to address the following CVEs:
* [CVE-2017-7657](http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2017-7657)
* [CVE-2017-7658](http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2017-7658)
* [CVE-2017-7656](http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2017-7656)
Signed-off-by: Fredrick Meunier <fmeunier@tyro.com>
> @brian-brazil Update jetty-servlet to 9.4.15.v20190215

- pom.xml
We would like to update the AWS SDK version to the current release 1.11.511 as 1.11.86 brings in httpclient 4.5.2 which has this directory traversal vulnerability: [HTTPCLIENT-1803](https://issues.apache.org/jira/browse/HTTPCLIENT-1803)
> Update AWS SDK to 1.11.511

- README.md
- src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java
- src/test/java/io/prometheus/cloudwatch/CloudWatchCollectorTest.java
When only one dimension is defined and a `aws_dimension_select` list is provided, the dimensions are known and do not have to be requested anymore.
This can result in substantial cost savings.
In our setup where we work a lot with temporary instances, we have for example 1000 times more metrics in cloudwatch than we have live instances.
By providing the cloudwatch_exporter a list of live instances via the `aws_dimension_select` property in its configuration file, we can keep the cost cloudwatch cost more under control.
> Do not request dimensions when they are stated

- Dockerfile
There are two improvements in this PR:
- Decrease build time: since we are using `builder` intermediate container we can skip cleanup step
- Decrease amount of meaningless messages during build process
> Improve build process

- src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java
- src/main/java/io/prometheus/cloudwatch/DynamicReloadServlet.java
- src/main/java/io/prometheus/cloudwatch/WebServer.java
- src/test/java/io/prometheus/cloudwatch/CloudWatchCollectorTest.java
Hi @brian-brazil! This PR is about these 2 items:
- Move away from deprecated sdk methods. Doing so, use the now standard builder pattern. In the case of AmazonCloudWatch, it now works with interface instead of direct implementation.
- Remove unused imports
Thanks
> Move away from deprecated SDK methods and cleanup imports

- pom.xml
Using IAM Service roles for EKS needs a newer version of the SDK.
Updating to the latest at the time of writing
> Update AWS SDK to 1.11.658

- src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java
- src/main/java/io/prometheus/cloudwatch/WebServer.java
I noticed when testing stuff locally, that if I point it to a file that doesn't exist calling `reader.close();` causes an error (NullPointerException) which hides the original error (FileNotFoundException)
This fixes that situation.
> Only close file if we opened a file.

- README.md
- src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java
- src/test/java/io/prometheus/cloudwatch/CloudWatchCollectorTest.java
Hi @brian-brazil,
As discussed with you in the latest #96 issue comments (item 2. : "if we happen to have the metadata for it"), this PR adds the resources tags as metric label in a new metric called `aws_resource_info`. This metric contains tags as labels for resources selected through `aws_tag_select`, and can later be joined to other metrics through PromQL queries.
Note that I have kept the empty `instance` label, even though I am not sure of the reason it is there, both in the case of the new metric and in other existing metrics. I'm curious to have your comment on that.
Thanks!
> Support resources tags as metric label

- src/test/java/io/prometheus/cloudwatch/CloudWatchCollectorTest.java
Hi @brian-brazil ,
As discussed in PR #233 , I'm adding here an enhancement to the unit test to cover the case of a resource with not tag when `tag_selection` is not specified under `aws_tag_select`.
The enhanced test fail without PR #233 , but succeed with it, as expected.
Thanks!
> Enhance unit test for resource with not tag when tag_selection is not specified

- README.md
- src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java
- src/test/java/io/prometheus/cloudwatch/CloudWatchCollectorTest.java
Adds support for falling back to the default region provider chain to fetch the region if omitted from the configuration file.
> Support default provider chain for region

- src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java
fixes #241
Label names does not follow the same matching rules as metric names.
https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels
> Fix label name strictness

- pom.xml
Version 1.11.704 includes a bugfix for IAM Roles for Service Accounts (IRSA):
https://github.com/aws/aws-sdk-java/blob/master/CHANGELOG.md#111704-2020-01-09
This adjusts the priority of the `AWS_WEB_IDENTITY_TOKEN_FILE` environment variable so it is accessed before instance metadata. This is required to use IRSA, as mentioned here: https://github.com/prometheus/cloudwatch_exporter/pull/224#issuecomment-572397938
> Update AWS SDK to 1.11.708

- README.md
The ONBUILD command expects `config.yml` to be in the same directory as the `Dockerfile`, not nested in a config directory. The readme was unclear on this point, causing me around five minutes of confusion until I read the parent `Dockerfile`. (This is a separate fix from #204.)
> correct config.yml steps for building own image

- Dockerfile
- README.md
The ONBUILD statement in the Dockerfile makes a assumptions about why the image may be built which are very specific and creates unecessary  future dependencies.  It's not really what the 'ONBUILD' command [was introduced for](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/). Removing it better aligns with the Docker Principle of build once, use anywhere and not having dependencies on the OS.
The intended capability of adding a `config.yml` file into the image can still easily be achieved.
https://github.com/prometheus/cloudwatch_exporter/issues/72 seems to be saying the same thing
> Remove onbuild

- src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java
Hi @brian-brazil ,
When we first used the Cloudwatch exporter, we noticed that the exporter was doing an initial scrape on startup. Although we didn't pay too much attention to it initially, this behaviour now slows down a lot our automated deployments, especially on large setups where multiple exporters are called and where scrape durations are around 30 seconds.
This PR will makes the collector to implement `Describable` in order to prevent the `CollectorRegistry` to fall back on the initial `collect()` on registration.
Thanks!
> Implement describe() to prevent the scrape on startup

- pom.xml
**Before:**
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] Source option 6 is no longer supported. Use 7 or later.
[ERROR] Target option 6 is no longer supported. Use 7 or later.
[INFO] 2 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
**After:**
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
Alternatively, one could also remove this so that the default takes over: https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-source-and-target.html
> allow maven-compiler-plugin to compile without a JDK downgrade

- README.md
- pom.xml
- src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java
- src/test/java/io/prometheus/cloudwatch/CloudWatchCollectorTest.java
I have the problem that a lot of the dimensions on my CloudWatch metrics change frequently. Because the default behaviour of `listMetrics()` is to return every metric that matches your query and has been updated in the last 2 weeks, this causes the scrape time to be very high. With this option, we can limit the returned metrics to only those which have been updated in the last 3 hours. I also had to update the AWS SDK to allow this, as the version currently being used doesn't have this feature
cc @brian-brazil
> Use `RecentlyActive` feature to only list metrics older than 3 hours when necessary

- pom.xml
A vulnerability scan of the `prom/cloudwatch-exporter` image finds this.
|      CVE       | SEVERITY | CVSS |      PACKAGE       |     VERSION      |    STATUS     |  PUBLISHED  | DISCOVERED |                    DESCRIPTION                     |
|----------------|----------|------|--------------------|------------------|---------------|-------------|------------|----------------------------------------------------|
| CVE-2017-18640 | high     | 7.50 | org.yaml_snakeyaml | 1.17             | fixed in 1.26 | > 10 months | < 1 hour   | The Alias feature in SnakeYAML 1.18 allows entity expansion during a load operation, a related issue to CVE-2003-1564.|
The [CVE](https://nvd.nist.gov/vuln/detail/CVE-2017-18640) description implies that it was introduced in `1.18` so it might be a false …
> Bump snakeyaml to 1.27

- .circleci/config.yml
This ensures that when a new Docker image is released it will be based on the latest available OpenJDK 11 image.
The currently released `0.9.0` Docker image is based on OpenJDK 11.0.8 which has some known vulnerabilities.
As the Dockerfile specifies a non-specific base image tag the image will be built with whatever version of OpenJDK 11 happens to be cached locally. With this change it will force the latest image pointed to by the tag `11-jre-slim` to be used as the base image, currently `11.0.9.1-jre-slim` (`sha256:28b59dc9a129c75349418e3b75508fd8eef3b33dd7d796079d1d19445d907776`).
The alternative to this would be to use a more specific tag for the base image, so `11.0.9-jre-slim` maybe.
> Pull latest openjdk:11 base image when building the Docker image

- pom.xml
Fixes [CVE-2020-27216](https://nvd.nist.gov/vuln/detail/CVE-2020-27216)
> Bump jetty-servlet to 9.4.15.v20190215

- pom.xml
Fixes [CVE-2020-25649](https://nvd.nist.gov/vuln/detail/CVE-2020-25649).
> Bump jackson-databind to 2.10.5.1

- pom.xml
Fixes the error `Failed to load class "org.slf4j.impl.StaticLoggerBinder"`
See [AWS docs](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/logging-slf4j.html) for more information.
> Add logging implementation for AWS SDK

- MAINTAINERS.md
Yesterday at the dev-summit, the Prometheus team has proposed @matthiasr as the new maintainer for this repo after @brian-brazil's retirement from the project. We are also still looking for a co-maintainer who has worked with this exporter more closely than @matthiasr.
This change will only be merged after an announcement on the prometheus-developers mailing list and is subject to lazy consensus.
Thank you, @brian-brazil, for the incredible amount of work done in this repository and for the project in general.
> Change maintainer from @brian-brazil to @matthiasr

- README.md
I ran into an issue where I could not find the right configuration to retrieve Kafka metrics from Cloudwatch.
Then I saw this comment: https://github.com/prometheus/cloudwatch_exporter/issues/237#issuecomment-581895552, and found out that in order for the metrics to work, you need to specify exactly all the aws_dimensions in order to be able to retrieve any metrics at all.
This change in the README reflects that.
However, the way it currently works I would suggest removing the `aws_dimensions` option altogether, as it only causes confusion without providing any actual configuration options.
> Update aws_dimensions config documentation

- example.yml
This PR contains the following changes
- Set the correct ELB values for `aws_namespace` and `aws_dimensions`. The current values will result in metrics not being populated. 
- Remove unavailable metrics `SurgeQueueLength` and `Latency`
To get the correct namespace and dimensions values, run the commands
-  ```aws cloudwatch list-metrics --namespace AWS/ApplicationELB```
-  ```aws cloudwatch list-metrics --namespace AWS/NetworkELB```
> Update example.yml with correct ELB values

- .circleci/config.yml
using "docker buildx" now building for arch's linux/amd64 and linux/arm64
related to issue #337
> update circleci to build multi-arch images

- .circleci/config.yml
> circleci: Pass BUILDX_PLATFORMs when building multi-arch images

- .circleci/config.yml
- Dockerfile
- pom.xml
Follow-up to #372, #374, #363.
Update the base images used in docker builds. Install Maven from the
tarball, apt pulls in the wrong JDK as a dependency.
Set up the context and builder for buildx.
Work around a bug in Java 13+ on linux/arm64 by using the older "vfork"
method. Update the surefire plugin.
Always run the image build, even for PRs, so that we can catch breakage
here before it hits the main branch.
cc @lht
> Fix Docker builds on linux/arm64

- pom.xml
instead of prefixing everything with `cloudwatch_exporter-` again.
This is at least one step towards #354.
> Use the Prometheus customary vX.Y.Z tag format

- Dockerfile
The Maven project unpublish patch versions from their CDN as soon as
they release a patch version. To avoid breaking the build every time
this happens (and repeated PR rebasing), use the archive URL instead.
> Use a stable download URL for Maven

- README.md
The CloudWatch exporter is very flexible, but does not serve all use
cases perfectly. Proof of this is the existence and success of YACE.
Link to it, so that users can make an informed choice.
> Link to alternatives

- .circleci/config.yml
- CONTRIBUTING.md
- README.md
- RELEASING.md
**HOLD** until 2021-11-29
Push images to both Docker Hub and Quay.io.
Only tag releases as `latest`, in line with what we previously did
manually for Docker Hub.
Publish per-release tags, using the tags as chosen by
maven-release-plugin, now `vX.Y.Z` as of #377.
Publish `main` (and `master` for consistency with other Prometheus
projects)
Fixes #354.
> Update and unify Docker image tagging scheme

- README.md
Modified some recent infrastructure as code that utilized this cloudwatch exporter that could help solve issues https://github.com/prometheus/cloudwatch_exporter/issues/356 & https://github.com/prometheus/cloudwatch_exporter/issues/356.
I added a comment linking to the source code for the builder and @matthiasr suggested a PR to add a link to the README.md
> Add config builder link to README.md

- examples/EBS.yml
- examples/NetworkELB.yml
Hey guys,
While working with your examples I noticed some metrics repeat themselves (either exactly with the same statistic or with a different statistic - which can be merged into one item)
> remove redundancy in examples of EBS & NetworkELB

- Dockerfile
Since #386, they started to provide a JRE image. As `openjdk:17-slim-bullseye` is `openjdk:17-jdk-slim-bullseye`; it really creates a big image for little benefits.
Eclipse Temurin is the new cool kid, http://whichjdk.com/ - https://blog.adoptopenjdk.net/2021/03/transition-to-eclipse-an-update/
> feat: migrate from OpenJDK to Eclipse Temurin

- .circleci/config.yml
This context prevented the build from running for external contributors,
but it is not needed as the PR build explicitly does not log in to the
Docker registries.
Missed this bit in 77c930795c3ade6f29072a92f0cf842e84f69d7e.
> Remove org-context from PR Docker Image build

- .circleci/config.yml
- CONTRIBUTING.md
- README.md
- pom.xml
- src/main/java/io/prometheus/cloudwatch/BuildInfoCollector.java
- src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java
- src/main/java/io/prometheus/cloudwatch/DataGetter.java
- src/main/java/io/prometheus/cloudwatch/DynamicReloadServlet.java
- src/main/java/io/prometheus/cloudwatch/GetMetricDataDataGetter.java
- src/main/java/io/prometheus/cloudwatch/GetMetricStatisticsDataGetter.java
- src/main/java/io/prometheus/cloudwatch/HealthServlet.java
- src/main/java/io/prometheus/cloudwatch/HomePageServlet.java
- src/main/java/io/prometheus/cloudwatch/ReloadSignalHandler.java
- src/main/java/io/prometheus/cloudwatch/WebServer.java
- src/test/java/io/prometheus/cloudwatch/CloudWatchCollectorTest.java
- src/test/java/io/prometheus/cloudwatch/GetMetricDataGetterTest.java
- src/test/java/io/prometheus/cloudwatch/RequestsMatchers.java
Resolves #417 :-) 
Note: this requires JDK > 11
The first commit is adding a maven plugin that can check and auto-fix formatting + adds CircleCI step that fails if somehow the developer forgot to format. You can see the CircleCI failure (as the code is not formatted).
The second commit is after applying the plugin format.
> Added automatic code formatter

- .circleci/config.yml
- pom.xml
- src/main/java/io/prometheus/cloudwatch/DynamicReloadServlet.java
- src/main/java/io/prometheus/cloudwatch/GetMetricDataDataGetter.java
- src/main/java/io/prometheus/cloudwatch/HealthServlet.java
- src/main/java/io/prometheus/cloudwatch/HomePageServlet.java
- src/main/java/io/prometheus/cloudwatch/WebServer.java
Fixes #390 ... + 
1. Moving repeated versions to maven properties (aws, prometheus)
2. Updating prometheus - 0.14.1 --> 0.15.0
3. Updating jetty - 10.0.8 --> 11.0.9
4. commons-coden 1.13 --> 1.15
5. Updating maven compiler plugin and release level.
6. Updated CircleCI image to `cimg/openjdk:17.0.3` (instead of deprecated openjdk image)
> Update maven dependencies (jetty 10->11)

- README.md
- src/main/java/io/prometheus/cloudwatch/GetMetricDataDataGetter.java
Fixing compiler warnings + spelling on `GetMetricDataDataGetter.java` + added note about new permission requirements to the README
> [GetMetricData] Fixed compiler warnings + README permission note

- src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java
Relates to #432  - print warning in case dimensions is empty. 
Otherwise - it's hard to understand that configuration is wrong.
I wonder though if there is any scenario where the case of empty dimensions is actually okay. 
If there are - then this warning may be spamming and wrong.
> Log warning in case of listDimensions returns empty list

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/request.md
Hi,
I want to address the problem of issues being open with insufficient information.
I suggest splitting our issues into three kinds:
I think using the [Github issue template](https://docs.github.com/en/enterprise-server@3.1/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser) can help minimize missing information.
The template picker would look +- like this upon opening a new issue:
As always - feel free to suggest more / fewer fields or alternative wording.
Thanks!
> Github Issues templates

- src/main/java/io/prometheus/cloudwatch/DisallowHttpMethods.java
- src/main/java/io/prometheus/cloudwatch/WebServer.java
Even though I believe there is no actual risk of [Cross-Site Tracing][xst] attacks in cloudwatch-exporter, disallowing
the `TRACE` HTTP method in Jetty reduces attack surface and makes security scans happier.
(Non-embedded) Jetty disables `TRACE` [in the default configuration][jetty-webapp] by forcing requests using that method be authenticated. I thought using a customizer would be cleaner and, as a bonus, would also be able to return a more accurate HTTP status code (405 Method Not Allowed).
[xst]: https://owasp.org/www-community/attacks/Cross_Site_Tracing
[jetty-webapp]: https://github.com/eclipse/jetty.project/blob/jetty-11.0.11/jetty-webapp/src/main/config/etc/webdefault.xml#L423-L440
> Disallow TRACE HTTP method

- README.md
- pom.xml
- src/main/java/io/prometheus/cloudwatch/CachingDimensionSource.java
- src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java
- src/main/java/io/prometheus/cloudwatch/DefaultDimensionSource.java
- src/main/java/io/prometheus/cloudwatch/DimensionSource.java
- src/main/java/io/prometheus/cloudwatch/GetMetricDataDataGetter.java
- src/main/java/io/prometheus/cloudwatch/GetMetricStatisticsDataGetter.java
- src/main/java/io/prometheus/cloudwatch/MetricRule.java
- src/test/java/io/prometheus/cloudwatch/CachingDimensionExpiryTest.java
- src/test/java/io/prometheus/cloudwatch/CachingDimensionSourceTest.java
- src/test/java/io/prometheus/cloudwatch/CloudWatchCollectorTest.java
This changes uses the [Caffeine](https://github.com/ben-manes/caffeine) library to provide the mechanism to cache results of the ListMetrics API. This can be configured using the global or metric level setting `list_metrics_cache_ttl` which specifies the TTL in seconds. I have initially opted to include a default value which results in no caching.
For example:
At a global level
```
region: eu-west-1
list_metrics_cache_ttl: 600 # 600 seconds
metrics: 
..
```
At a metric level
```
- aws_dimensions:
- InstanceId
aws_metric_name: CPUUtilization
aws_namespace: AWS/EC2
aws_statistics:
- Average
list_metrics_cache_ttl: 300 # 300 seconds
aws_tag_select:
tag_selections:
Monitoring: ["enabled"]
resource_type_selection: ec2:instance
resource_id_dimension: InstanceId
```
Questions
- Is introducing an …
> Cache calls to ListMetrics 

- pom.xml
CVE-2022-38752
CVE-2022-25857
both are YAML parsing issues on untrusted input, so are unlikely to be exposed unless someone is providing CWE-as-a-Service. Nonetheless, we upgrade to keep things neat.
> Update snakeyaml to 1.32 for security updates

- README.md
- src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java
- src/main/java/io/prometheus/cloudwatch/DefaultDimensionSource.java
- src/main/java/io/prometheus/cloudwatch/MetricRule.java
> list-metrics-warnings made configurable

- src/main/java/io/prometheus/cloudwatch/GetMetricDataDataGetter.java
As I read the existing code, it's trying to count the number of GetMetricData API calls made, but AWS is billing for every statistic within that. I'm seeing a discrepancy between what cloudwatch_exporter reports and what AWS bills us by a factor of 2-5x, depending on how I slice it.
Per the [AWS documentation](https://aws.amazon.com/cloudwatch/pricing/), "You can request up to five statistics for the same metric in a single GetMetricData API request. Additional statistics are billed as an additional metric."
So even though we can coalesce multiple statistics into a single API call, they're billed by AWS as if they were in individual API calls, so we should be measuring the full count, not dividing by five, to properly account for what AWS is charging.
> Fix measurement of cloudwatch_metrics_requested_total

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/metrics.md
- .github/ISSUE_TEMPLATE/request.md
These are commonly reported as "bugs" but are really down to
peculiarities in CloudWatch. Add a separate issue template and collect
more information that will help with this.
> Add issue template for metrics issues

- pom.xml
To address security issues in transitive dependencies (Netty) as per #485
> Update AWS SDK to 2.20.5

- .github/dependabot.yaml
- .github/workflows/maven.yml
Add GitHub Actions workflow to test with Maven, and submit dependencies so that dependabot can at least alert about issues in transitive dependencies.
> GH Actions workflow for a better dependabot

- pom.xml
- src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java
We don't *need* unsafe YAML deserialization, so make sure we don't. It
is unlikely but not unthinkable that someone might load an untrusted
configuration.
> Use safe YAML loading

- .circleci/config.yml
to fix issues with binfmt after the CircleCI infrastructure migration
> Update Prometheus common orb

- README.md
This comes up frequently, because it is confusing unless you understand the
intricacies of the Prometheus data and query model, CloudWatch metrics
convergence, and the relevant settings.
Fixes #580.
Explanation adapted from https://github.com/prometheus/cloudwatch_exporter/issues/483#issuecomment-1425515511.
> Document common "I see no data" question

- pom.xml
This PR bumps the AWS SDK to pull in a newer version of Netty as v4.1.107.Final has been flagged with a CVE https://nvd.nist.gov/vuln/detail/CVE-2024-29025 for io.netty_netty-codec-http
Confirmed newer version of affected package is pulled in 
```
Downloading from central: https://repo.maven.apache.org/maven2/io/netty/netty-codec-http/4.1.111.Final/netty-codec-http-4.1.111.Final.pom
Downloaded from central: https://repo.maven.apache.org/maven2/io/netty/netty-codec-http/4.1.111.Final/netty-codec-http-4.1.111.Final.pom (4.4 kB at 546 kB/s)
```
> Update pom.xml to use newer version of AWS SDK

- src/main/java/io/prometheus/cloudwatch/GetMetricDataDataGetter.java
This change fixes how the exporter counts the metrics that will be billed for the GetMetricData request.
The YACE already fixed this in their implementation as seen here: https://github.com/nerdswords/yet-another-cloudwatch-exporter/blob/master/pkg/clients/cloudwatch/v2/client.go#L117
**EXAMPLE**
```
MetricDataQueries=[
{
'Id': 'foo',
'MetricStat': {
'Metric': {
'Namespace': 'AWS/DynamoDB',
'MetricName': 'ConsumedWriteCapacityUnits',
'Dimensions': [
{'Name': 'TableName',
'Value': 'one-table'}
]
},
'Period': 300,   # 5 minutes
'Stat': 'Sum',
'Unit': 'Count'
},
'ReturnData': True,
},
{
'Id': 'bar',
'MetricStat': {
'Metric': {
'Namespace': 'AWS/DynamoDB',
'MetricName': 'ConsumedWriteCapacityUnits',
'Dimensions': [
{'Name': 'TableName',
'Value': 'another-table'}
]
},
'Period': 300,   # 5 …
```
> fix how the metricRequestedForBilling is counted to use queries.size()

- pom.xml
NettyIO has a CVE https://nvd.nist.gov/vuln/detail/CVE-2024-47535 thats fixed in version `4.1.115`. 
Version 2.29.12 of the AWS SDK https://github.com/aws/aws-sdk-java-v2/commits/2.29.12/ includes this PR https://github.com/aws/aws-sdk-java-v2/commit/b1a52e9e38a91afbade0f4c5ef55b5be3492aff0 which pulls in the fixed version of Netty
> Bump AWS aws-sdk-java-v2 to pull in a fix for a NettyIO CVE-2024-47535
